local button = require "in.button"

function init(self)
	button.acquire()

	button.register("save/button", function()
		msg.post(".", "save")
	end)
	button.register("load/button", function()
		msg.post(".", "load")
	end)
	button.register("random/button", function()
		msg.post(".", "random")
	end)
end

function on_input(self, action_id, action)
	button.on_input(action_id, action)
end

function on_reload(self)
	-- Add input-handling code here
	-- Remove this function if not needed
end
