local test_input = require "test.test_input"
local test_broadcast = require "test.test_broadcast"
local test_flow = require "test.test_flow"
local test_timer = require "test.test_timer"
local test_savefile = require "test.test_savefile"

local deftest = require "deftest.deftest"

function init(self)
	deftest.add(test_input)
	deftest.add(test_broadcast)
	deftest.add(test_flow)
	deftest.add(test_timer)
	deftest.add(test_savefile)
	deftest.run()
end
