local test_broadcast = require "test.test_broadcast"
local test_flow = require "test.test_flow"
local test_savetable = require "test.test_savetable"
local test_savefile = require "test.test_savefile"
local test_file = require "test.test_file"
local test_settings = require "test.test_settings"
local test_listener = require "test.test_listener"

local deftest = require "deftest.deftest"

function init(self)
	deftest.add(test_broadcast)
	deftest.add(test_flow)
	deftest.add(test_savetable)
	deftest.add(test_savefile)
	deftest.add(test_file)
	deftest.add(test_listener)
	deftest.add(test_settings)
	deftest.run()
end
