local logger = require "ludobits.m.logger"

local log = logger.create("[script]")

function init(self)
	log("init")
end

function on_input(self, action_id, action)
	if action_id == hash("touch") then
		if action.released then
			log.i("released mouse button")
		elseif action.pressed then
			log.i("pressed mouse button")
		end
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Remove this function if not needed
end
