local button = require "in.button"
local some_data = require "examples.listener.some_data"


function init(self)
	button.acquire()
	button.register("foo/button", function()
		some_data.trigger_foo()
	end)
	button.register("bar/button", function()
		some_data.trigger_bar()
	end)
end

function final(self)
	button.release()
	button.unregister()
end

function on_input(self, action_id, action)
	button.on_input(action_id, action)
end
