name: CI

on: [push]

jobs:
    build_and_run:
        name: Build and run
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
          - uses: coactions/setup-xvfb@v1
            with:
                java-version: '21.0.5+11.0.LTS'
                distribution: 'temurin'
          - name: Run.sh
            env:
                DEFOLD_USER: foo
                DEFOLD_AUTH: bar
                DEFOLD_BOOSTRAP_COLLECTION: /test/test.collectionc
            run: ./.test/run.sh
